In [ ]:
# Matrix Addition and Subtraction

In [ ]:
import numpy as np
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

matrix_sum = matrix_a + matrix_b
print("Matrix Addition:\n", matrix_sum)

matrix_diff = matrix_a - matrix_b
print("\nMatrix Subtraction:\n", matrix_diff)

Matrix Addition:
 [[ 6  8]
 [10 12]]

Matrix Subtraction:
 [[-4 -4]
 [-4 -4]]


In [ ]:
#Matrix Multiplication

In [ ]:
matrix_mul = matrix_a * matrix_b
print("\nMultiplication:\n", matrix_mul)

# Dot product
matrix_dot = np.dot(matrix_a, matrix_b)
print("\nMatrix Dot Product:\n", matrix_dot)


Multiplication:
 [[ 5 12]
 [21 32]]

Matrix Dot Product:
 [[19 22]
 [43 50]]


In [ ]:
# Transpose of a matrix
transpose_a = np.transpose(matrix_a)
print("\nMatrix Transpose:\n", transpose_a)



Matrix Transpose:
 [[1 3]
 [2 4]]
